// Generated by nui — do not edit.
// Logic interface for the `TodoList` component (IR format v1).
//
// Implement each function in the crate root, exactly as follows
// (param names matter: UniFFI derives the Swift labels from them):
//
//     #[uniffi::export]
//     pub fn todo_list_add(todos: Vec<TodoListTodo>) -> Vec<TodoListTodo>
//     #[uniffi::export]
//     pub fn todo_list_clear(todos: Vec<TodoListTodo>) -> Vec<TodoListTodo>
//
// Re-export the record types next to the `mod` declaration so the
// implementations can use them:
//
//     pub use <this module>::*;

/// The `Todo` record from the `.nui` file, prefixed with the component
/// name so the UniFFI-generated Swift never collides with the UI-side
/// struct of the same name.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct TodoListTodo {
    pub title: String,
}

/// Fails the build if any declared logic function is missing or its
/// signature drifts from the `.nui` declaration.
#[allow(dead_code)]
fn _nui_check_logic_signatures() {
    let _: fn(Vec<TodoListTodo>) -> Vec<TodoListTodo> = crate::todo_list_add;
    let _: fn(Vec<TodoListTodo>) -> Vec<TodoListTodo> = crate::todo_list_clear;
}
