// Generated by nui — do not edit.
// Logic interface for the `Toggle` component (IR format v1).
//
// Implement each function in the crate root, exactly as follows
// (param names matter: UniFFI derives the Swift labels from them):
//
//     #[uniffi::export]
//     pub fn toggle_toggle(value: bool) -> bool

/// Fails the build if any declared logic function is missing or its
/// signature drifts from the `.nui` declaration.
#[allow(dead_code)]
fn _nui_check_logic_signatures() {
    let _: fn(bool) -> bool = crate::toggle_toggle;
}
