// Generated by nui — do not edit.
// Logic interface for the `Profile` component (IR format v1).
//
// Implement each function in the crate root, exactly as follows
// (param names matter: UniFFI derives the Swift labels from them):
//
//     #[uniffi::export]
//     pub fn profile_next(current: ProfilePerson) -> ProfilePerson
//
// Re-export the record types next to the `mod` declaration so the
// implementations can use them:
//
//     pub use <this module>::*;

/// The `Person` record from the `.nui` file, prefixed with the component
/// name so the UniFFI-generated Swift never collides with the UI-side
/// struct of the same name.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct ProfilePerson {
    pub name: String,
    pub bio: String,
}

/// Fails the build if any declared logic function is missing or its
/// signature drifts from the `.nui` declaration.
#[allow(dead_code)]
fn _nui_check_logic_signatures() {
    let _: fn(ProfilePerson) -> ProfilePerson = crate::profile_next;
}
