// Generated by nui — do not edit.
// Logic interface for the `Counter` component (IR format v1).
//
// Implement each function in the crate root, exactly as follows
// (param names matter: UniFFI derives the Swift labels from them):
//
//     #[uniffi::export]
//     pub fn counter_increment(count: i64) -> i64
//     #[uniffi::export]
//     pub fn counter_decrement(count: i64) -> i64

/// Fails the build if any declared logic function is missing or its
/// signature drifts from the `.nui` declaration.
#[allow(dead_code)]
fn _nui_check_logic_signatures() {
    let _: fn(i64) -> i64 = crate::counter_increment;
    let _: fn(i64) -> i64 = crate::counter_decrement;
}
