//! Rust logic backend: generates the logic-crate interface from the `.nui`
//! `logic` block, so the UI and the logic layer share one source of truth.
//!
//! nui owns the state; the backend owns the logic. Each declared
//! `fn increment(count: Int) -> Int` must be implemented in the crate root
//! as a UniFFI-exported free function, prefixed with the component name so
//! the generated Swift never collides with other symbols in the app target:
//!
//! ```ignore
//! #[uniffi::export]
//! pub fn counter_increment(count: i64) -> i64 { ... }
//! ```
//!
//! The generated file contains a compile-time signature check: if the crate
//! is missing a function, or a signature drifts from the `.nui` declaration,
//! `cargo build` fails.

use std::fmt::Write as _;

use crate::ir;

pub fn generate(doc: &ir::Document) -> String {
    let component = &doc.component;
    let name = &component.name;
    let prefix = snake_case(name);
    let mut out = String::new();

    let _ = writeln!(out, "// Generated by nui — do not edit.");
    let _ = writeln!(
        out,
        "// Logic interface for the `{name}` component (IR format v{}).",
        doc.format_version
    );
    let _ = writeln!(out, "//");
    let _ = writeln!(
        out,
        "// Implement each function in the crate root, exactly as follows"
    );
    let _ = writeln!(
        out,
        "// (param names matter: UniFFI derives the Swift labels from them):"
    );
    let _ = writeln!(out, "//");
    for function in &component.functions {
        let _ = writeln!(out, "//     #[uniffi::export]");
        let _ = writeln!(
            out,
            "//     pub fn {}({}) -> {}",
            rust_fn_name(&prefix, &function.name),
            rust_params(function),
            rust_type(function.returns)
        );
    }
    out.push('\n');

    let _ = writeln!(
        out,
        "/// Fails the build if any declared logic function is missing or its"
    );
    let _ = writeln!(out, "/// signature drifts from the `.nui` declaration.");
    let _ = writeln!(out, "#[allow(dead_code)]");
    let _ = writeln!(out, "fn _nui_check_logic_signatures() {{");
    for function in &component.functions {
        let param_types: Vec<&str> = function
            .params
            .iter()
            .map(|param| rust_type(param.ty))
            .collect();
        let _ = writeln!(
            out,
            "    let _: fn({}) -> {} = crate::{};",
            param_types.join(", "),
            rust_type(function.returns),
            rust_fn_name(&prefix, &function.name)
        );
    }
    let _ = writeln!(out, "}}");

    out
}

/// `Counter` + `fetchData` → `counter_fetch_data`.
pub fn rust_fn_name(component_prefix: &str, function: &str) -> String {
    format!("{component_prefix}_{}", snake_case(function))
}

fn rust_params(function: &ir::FunctionDecl) -> String {
    function
        .params
        .iter()
        .map(|param| format!("{}: {}", snake_case(&param.name), rust_type(param.ty)))
        .collect::<Vec<_>>()
        .join(", ")
}

fn rust_type(ty: ir::Type) -> &'static str {
    match ty {
        ir::Type::Int => "i64",
        ir::Type::Float => "f64",
        ir::Type::Bool => "bool",
        ir::Type::String => "String",
    }
}

/// `Counter` → `counter`, `TodoList` → `todo_list`, `fetchData` → `fetch_data`.
pub fn snake_case(name: &str) -> String {
    let mut out = String::new();
    for (i, c) in name.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}
