//! Swift backend: transpiles the IR into a single, drop-in SwiftUI file.
//!
//! For a component named `Counter` the generated file contains:
//!
//! - `CounterState` — value struct from the `state` declarations; the UI
//!   owns this state
//! - `CounterLogic` — protocol with one async method per declared `fn`,
//!   implemented by the logic layer (e.g. UniFFI bindings of a Rust
//!   XCFramework via the generated bridge)
//! - `CounterStore` — `@Observable` store with one method per view action;
//!   each method calls a logic function and assigns the result to state
//! - `CounterView` — the SwiftUI view tree
//! - a DEBUG-only `#Preview` with a stub logic returning default values
//!
//! Requires iOS 17 / macOS 14 (the `@Observable` macro).

use crate::ir;

pub fn generate(doc: &ir::Document) -> String {
    let component = &doc.component;
    let actions = ActionMethods::collect(component);
    let mut w = Writer::default();

    w.line("// Generated by nui — do not edit.");
    w.line(format!(
        "// Component: {} (IR format v{})",
        component.name, doc.format_version
    ));
    w.blank();
    w.line("import SwiftUI");
    w.blank();

    emit_state(&mut w, component);
    emit_logic(&mut w, component);
    emit_store(&mut w, component, &actions);
    emit_view(&mut w, component, &actions);
    emit_preview(&mut w, component);

    w.out
}

/// Every distinct action in the view tree becomes one generated store
/// method (`count = increment(count)` → `func incrementCount()`).
/// Shared with the UIKit backend so both emit identical store methods.
pub(crate) struct ActionMethods {
    pub(crate) methods: Vec<(ir::Action, String)>,
}

impl ActionMethods {
    pub(crate) fn collect(component: &ir::Component) -> Self {
        let mut methods: Vec<(ir::Action, String)> = Vec::new();
        collect_actions(&component.root, &mut |action| {
            if methods.iter().any(|(existing, _)| existing == action) {
                return;
            }
            let base = format!("{}{}", action.function, upper_first(&action.state));
            let mut name = base.clone();
            let mut suffix = 2;
            while methods.iter().any(|(_, taken)| *taken == name) {
                name = format!("{base}{suffix}");
                suffix += 1;
            }
            methods.push((action.clone(), name));
        });
        Self { methods }
    }

    pub(crate) fn name_for(&self, action: &ir::Action) -> &str {
        self.methods
            .iter()
            .find(|(existing, _)| existing == action)
            .map(|(_, name)| name.as_str())
            .expect("every action was collected")
    }
}

fn collect_actions(node: &ir::Node, f: &mut impl FnMut(&ir::Action)) {
    match node {
        ir::Node::Button { action, .. } => f(action),
        ir::Node::VStack { children, .. }
        | ir::Node::HStack { children, .. }
        | ir::Node::List { children, .. } => {
            for child in children {
                collect_actions(child, f);
            }
        }
        _ => {}
    }
}

pub(crate) fn upper_first(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

pub(crate) fn emit_state(w: &mut Writer, component: &ir::Component) {
    let name = &component.name;
    w.line("// MARK: - State");
    w.blank();
    w.line(format!("public struct {name}State: Equatable, Sendable {{"));
    w.indented(|w| {
        for decl in &component.state {
            w.line(format!(
                "public var {}: {}",
                decl.name,
                swift_type(decl.ty)
            ));
        }
        if !component.state.is_empty() {
            w.blank();
        }
        let params: Vec<String> = component
            .state
            .iter()
            .map(|decl| {
                format!(
                    "{}: {} = {}",
                    decl.name,
                    swift_type(decl.ty),
                    value_literal(&decl.initial)
                )
            })
            .collect();
        w.line(format!("public init({}) {{", params.join(", ")));
        w.indented(|w| {
            for decl in &component.state {
                w.line(format!("self.{0} = {0}", decl.name));
            }
        });
        w.line("}");
    });
    w.line("}");
    w.blank();
}

pub(crate) fn emit_logic(w: &mut Writer, component: &ir::Component) {
    let name = &component.name;
    w.line("// MARK: - Logic");
    w.blank();
    w.line("/// The typed interface declared in the `.nui` logic block, implemented");
    w.line("/// by the backend (e.g. Rust behind UniFFI via the generated bridge).");
    w.line("/// The UI owns the state; these pure functions compute new values.");
    w.line(format!("public protocol {name}Logic: Sendable {{"));
    w.indented(|w| {
        for function in &component.functions {
            w.line(protocol_method(function));
        }
    });
    w.line("}");
    w.blank();
}

pub(crate) fn protocol_method(function: &ir::FunctionDecl) -> String {
    let params: Vec<String> = function
        .params
        .iter()
        .map(|param| format!("{}: {}", param.name, swift_type(param.ty)))
        .collect();
    format!(
        "func {}({}) async -> {}",
        function.name,
        params.join(", "),
        swift_type(function.returns)
    )
}

fn emit_store(w: &mut Writer, component: &ir::Component, actions: &ActionMethods) {
    let name = &component.name;
    w.line("// MARK: - Store");
    w.blank();
    w.line("@Observable @MainActor");
    w.line(format!("public final class {name}Store {{"));
    w.indented(|w| {
        w.line(format!("public var state: {name}State"));
        w.line(format!("private let logic: any {name}Logic"));
        w.blank();
        w.line(format!(
            "public init(logic: any {name}Logic, state: {name}State = {name}State()) {{"
        ));
        w.indented(|w| {
            w.line("self.logic = logic");
            w.line("self.state = state");
        });
        w.line("}");
        for (action, method) in &actions.methods {
            w.blank();
            w.line(format!("public func {method}() {{"));
            w.indented(|w| {
                w.line("Task {");
                w.indented(|w| {
                    w.line(format!(
                        "state.{} = await logic.{}({})",
                        action.state,
                        action.function,
                        call_args(component, action)
                    ));
                });
                w.line("}");
            });
            w.line("}");
        }
    });
    w.line("}");
    w.blank();
}

pub(crate) fn call_args(component: &ir::Component, action: &ir::Action) -> String {
    // Labels come from the declared params; lowering checked args against them.
    let decl = component
        .functions
        .iter()
        .find(|f| f.name == action.function)
        .expect("action function was checked during lowering");
    action
        .args
        .iter()
        .zip(&decl.params)
        .map(|(arg, param)| {
            let value = match arg {
                ir::CallArg::State { name } => format!("state.{name}"),
                ir::CallArg::Value { value } => value_literal(value),
            };
            format!("{}: {}", param.name, value)
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn emit_view(w: &mut Writer, component: &ir::Component, actions: &ActionMethods) {
    let name = &component.name;
    w.line("// MARK: - View");
    w.blank();
    w.line(format!("public struct {name}View: View {{"));
    w.indented(|w| {
        w.line(format!("@Bindable public var store: {name}Store"));
        w.blank();
        w.line(format!("public init(store: {name}Store) {{"));
        w.indented(|w| w.line("self.store = store"));
        w.line("}");
        w.blank();
        w.line("public var body: some View {");
        w.indented(|w| emit_node(w, &component.root, actions));
        w.line("}");
    });
    w.line("}");
    w.blank();
}

fn emit_preview(w: &mut Writer, component: &ir::Component) {
    let name = &component.name;
    w.line("#if DEBUG");
    w.line("/// Preview stub returning default values. Real logic is injected");
    w.line("/// by the host app.");
    w.line(format!("private struct {name}PreviewLogic: {name}Logic {{"));
    w.indented(|w| {
        for function in &component.functions {
            w.line(format!(
                "{} {{ {} }}",
                protocol_method(function),
                default_value(function.returns)
            ));
        }
    });
    w.line("}");
    w.blank();
    w.line("#Preview {");
    w.indented(|w| {
        w.line(format!(
            "{name}View(store: {name}Store(logic: {name}PreviewLogic()))"
        ));
    });
    w.line("}");
    w.line("#endif");
}

pub(crate) fn default_value(ty: ir::Type) -> &'static str {
    match ty {
        ir::Type::Int => "0",
        ir::Type::Float => "0.0",
        ir::Type::Bool => "false",
        ir::Type::String => "\"\"",
    }
}

// --- view tree ---

fn emit_node(w: &mut Writer, node: &ir::Node, actions: &ActionMethods) {
    match node {
        ir::Node::Text { content, modifiers } => {
            w.line(format!("Text({})", text_literal(content)));
            emit_leaf_modifiers(w, modifiers);
        }
        ir::Node::Button {
            label,
            action,
            modifiers,
        } => {
            w.line(format!(
                "Button({}) {{ store.{}() }}",
                text_literal(label),
                actions.name_for(action)
            ));
            emit_leaf_modifiers(w, modifiers);
        }
        ir::Node::TextField {
            binding,
            placeholder,
            modifiers,
        } => {
            w.line(format!(
                "TextField({}, text: $store.state.{binding})",
                string_literal(placeholder.as_deref().unwrap_or(""))
            ));
            emit_leaf_modifiers(w, modifiers);
        }
        ir::Node::Image { source, modifiers } => {
            w.line(format!("Image({})", string_literal(source)));
            emit_leaf_modifiers(w, modifiers);
        }
        ir::Node::VStack {
            spacing,
            children,
            modifiers,
        } => emit_stack(w, "VStack", *spacing, children, modifiers, actions),
        ir::Node::HStack {
            spacing,
            children,
            modifiers,
        } => emit_stack(w, "HStack", *spacing, children, modifiers, actions),
        ir::Node::List {
            children,
            modifiers,
        } => {
            w.line("List {");
            w.indented(|w| {
                for child in children {
                    emit_node(w, child, actions);
                }
            });
            w.line("}");
            emit_container_modifiers(w, modifiers);
        }
        ir::Node::Spacer => w.line("Spacer()"),
    }
}

fn emit_stack(
    w: &mut Writer,
    kind: &str,
    spacing: Option<f64>,
    children: &[ir::Node],
    modifiers: &[ir::Modifier],
    actions: &ActionMethods,
) {
    match spacing {
        Some(value) => w.line(format!("{kind}(spacing: {}) {{", number(value))),
        None => w.line(format!("{kind} {{")),
    }
    w.indented(|w| {
        for child in children {
            emit_node(w, child, actions);
        }
    });
    w.line("}");
    emit_container_modifiers(w, modifiers);
}

/// Leaf modifiers go indented under the view (SwiftUI convention).
fn emit_leaf_modifiers(w: &mut Writer, modifiers: &[ir::Modifier]) {
    w.indented(|w| {
        for modifier in modifiers {
            w.line(modifier_call(modifier));
        }
    });
}

/// Container modifiers go at the same indent, after the closing brace.
fn emit_container_modifiers(w: &mut Writer, modifiers: &[ir::Modifier]) {
    for modifier in modifiers {
        w.line(modifier_call(modifier));
    }
}

fn modifier_call(modifier: &ir::Modifier) -> String {
    match modifier {
        ir::Modifier::Padding { value } => format!(".padding({})", number(*value)),
        ir::Modifier::Font { style } => format!(".font(.{})", font_name(*style)),
        ir::Modifier::ForegroundColor { color } => {
            format!(".foregroundStyle(.{})", color_name(*color))
        }
    }
}

// --- literals and names ---

pub(crate) fn swift_type(ty: ir::Type) -> &'static str {
    match ty {
        ir::Type::Int => "Int",
        ir::Type::Float => "Double",
        ir::Type::Bool => "Bool",
        ir::Type::String => "String",
    }
}

fn font_name(style: ir::FontStyle) -> &'static str {
    match style {
        ir::FontStyle::LargeTitle => "largeTitle",
        ir::FontStyle::Title => "title",
        ir::FontStyle::Headline => "headline",
        ir::FontStyle::Body => "body",
        ir::FontStyle::Caption => "caption",
    }
}

fn color_name(color: ir::Color) -> &'static str {
    match color {
        ir::Color::Primary => "primary",
        ir::Color::Secondary => "secondary",
        ir::Color::Red => "red",
        ir::Color::Green => "green",
        ir::Color::Blue => "blue",
        ir::Color::Orange => "orange",
        ir::Color::Yellow => "yellow",
        ir::Color::Purple => "purple",
        ir::Color::Gray => "gray",
    }
}

pub(crate) fn value_literal(value: &ir::Value) -> String {
    match value {
        ir::Value::Int(v) => v.to_string(),
        ir::Value::Float(v) => {
            let text = format!("{v}");
            if text.contains('.') || text.contains('e') {
                text
            } else {
                format!("{text}.0")
            }
        }
        ir::Value::Bool(v) => v.to_string(),
        ir::Value::String(s) => string_literal(s),
    }
}

/// Formats spacing/padding numbers, dropping a trailing `.0`.
pub(crate) fn number(value: f64) -> String {
    if value.fract() == 0.0 && value.abs() < 1e15 {
        format!("{}", value as i64)
    } else {
        format!("{value}")
    }
}

pub(crate) fn string_literal(text: &str) -> String {
    let mut out = String::from("\"");
    escape_into(text, &mut out);
    out.push('"');
    out
}

/// Interpolated text: `"Count: {count}"` → `"Count: \(store.state.count)"`.
pub(crate) fn text_literal(content: &ir::TextContent) -> String {
    let mut out = String::from("\"");
    for segment in &content.0 {
        match segment {
            ir::TextSegment::Literal { value } => escape_into(value, &mut out),
            ir::TextSegment::State { name } => {
                out.push_str("\\(store.state.");
                out.push_str(name);
                out.push(')');
            }
        }
    }
    out.push('"');
    out
}

fn escape_into(text: &str, out: &mut String) {
    for c in text.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
}

// --- output plumbing (shared with the UIKit backend) ---

#[derive(Default)]
pub(crate) struct Writer {
    pub(crate) out: String,
    pub(crate) indent: usize,
}

impl Writer {
    pub(crate) fn line(&mut self, text: impl AsRef<str>) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(text.as_ref());
        self.out.push('\n');
    }

    pub(crate) fn blank(&mut self) {
        self.out.push('\n');
    }

    pub(crate) fn indented(&mut self, f: impl FnOnce(&mut Self)) {
        self.indent += 1;
        f(self);
        self.indent -= 1;
    }
}
