//! Swift bridge backend: generates the adapter connecting the nui-generated
//! UI to the Rust logic crate.
//!
//! For `Counter` this emits `RustCounterLogic: CounterLogic`, one method per
//! declared logic function, each calling the UniFFI-generated free function
//! (`counter_increment` in Rust → `counterIncrement` in Swift) with the
//! `Int ↔ Int64` conversions handled. With this file generated, the only
//! handwritten code anywhere is the function bodies in the Rust crate.

use std::fmt::Write as _;

use crate::ir;
use crate::rust_logic::{rust_fn_name, snake_case};

pub fn generate(doc: &ir::Document) -> String {
    let component = &doc.component;
    let name = &component.name;
    let prefix = snake_case(name);
    let mut out = String::new();

    let _ = writeln!(out, "// Generated by nui — do not edit.");
    let _ = writeln!(
        out,
        "// Bridges the nui-generated `{name}` UI to the Rust logic crate via UniFFI."
    );
    out.push('\n');

    let _ = writeln!(out, "struct Rust{name}Logic: {name}Logic {{");
    for function in &component.functions {
        let params: Vec<String> = function
            .params
            .iter()
            .map(|param| format!("{}: {}", param.name, swift_type(param.ty)))
            .collect();
        let _ = writeln!(
            out,
            "    func {}({}) async -> {} {{",
            function.name,
            params.join(", "),
            swift_type(function.returns)
        );
        let args: Vec<String> = function
            .params
            .iter()
            .map(|param| format!("{}: {}", param.name, to_ffi(param)))
            .collect();
        let call = format!(
            "{}({})",
            uniffi_swift_name(&prefix, &function.name),
            args.join(", ")
        );
        let _ = writeln!(out, "        {}", from_ffi(function.returns, &call));
        let _ = writeln!(out, "    }}");
    }
    let _ = writeln!(out, "}}");

    out
}

/// Rust `counter_fetch_data` → UniFFI-generated Swift `counterFetchData`.
fn uniffi_swift_name(prefix: &str, function: &str) -> String {
    let snake = rust_fn_name(prefix, function);
    let mut out = String::new();
    let mut upper_next = false;
    for c in snake.chars() {
        if c == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn swift_type(ty: ir::Type) -> &'static str {
    match ty {
        ir::Type::Int => "Int",
        ir::Type::Float => "Double",
        ir::Type::Bool => "Bool",
        ir::Type::String => "String",
    }
}

/// nui Swift value → FFI value (only Int needs widening to Int64).
fn to_ffi(param: &ir::Param) -> String {
    match param.ty {
        ir::Type::Int => format!("Int64({})", param.name),
        _ => param.name.clone(),
    }
}

/// FFI result → nui Swift value.
fn from_ffi(ty: ir::Type, call: &str) -> String {
    match ty {
        ir::Type::Int => format!("Int({call})"),
        _ => call.to_string(),
    }
}
