//! Swift bridge backend: generates the adapter connecting the nui-generated
//! UI to the Rust logic crate.
//!
//! For `Counter` this emits `RustCounterLogic: CounterLogic`, one method per
//! declared logic function, each calling the UniFFI-generated free function
//! (`counter_increment` in Rust → `counterIncrement` in Swift) with the
//! `Int ↔ Int64` conversions handled. Record types cross the boundary by
//! field-wise conversion between the UI struct (`Person`) and the
//! component-prefixed UniFFI record (`ProfilePerson`); lists convert
//! element-wise with `map`. With this file generated, the only handwritten
//! code anywhere is the function bodies in the Rust crate.

use std::fmt::Write as _;

use crate::ir;
use crate::rust_logic::{rust_fn_name, rust_record_name, snake_case};
use crate::swift::{record_decl, swift_type};

pub fn generate(doc: &ir::Document) -> String {
    let component = &doc.component;
    let name = &component.name;
    let prefix = snake_case(name);
    let mut out = String::new();

    let _ = writeln!(out, "// Generated by nui — do not edit.");
    let _ = writeln!(
        out,
        "// Bridges the nui-generated `{name}` UI to the Rust logic crate via UniFFI."
    );
    out.push('\n');

    let _ = writeln!(out, "struct Rust{name}Logic: {name}Logic {{");
    for function in &component.functions {
        let params: Vec<String> = function
            .params
            .iter()
            .map(|param| format!("{}: {}", param.name, swift_type(&param.ty)))
            .collect();
        let _ = writeln!(
            out,
            "    func {}({}) async -> {} {{",
            function.name,
            params.join(", "),
            swift_type(&function.returns)
        );
        let args: Vec<String> = function
            .params
            .iter()
            .map(|param| format!("{}: {}", param.name, to_ffi(component, param)))
            .collect();
        let call = format!(
            "{}({})",
            uniffi_swift_name(&prefix, &function.name),
            args.join(", ")
        );
        match &function.returns {
            // Structured results get a named intermediate for readability.
            ty @ (ir::Type::Record(_) | ir::Type::List(_)) if needs_conversion(ty) => {
                let _ = writeln!(out, "        let result = {call}");
                let _ = writeln!(
                    out,
                    "        return {}",
                    from_ffi(component, ty, "result")
                );
            }
            ty => {
                let _ = writeln!(out, "        {}", from_ffi(component, ty, &call));
            }
        }
        let _ = writeln!(out, "    }}");
    }
    let _ = writeln!(out, "}}");

    out
}

/// Rust `counter_fetch_data` → UniFFI-generated Swift `counterFetchData`.
fn uniffi_swift_name(prefix: &str, function: &str) -> String {
    lower_camel(&rust_fn_name(prefix, function))
}

/// `full_name` → `fullName` (how UniFFI names record fields in Swift).
fn lower_camel(snake: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for c in snake.chars() {
        if c == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// The Swift-side label of a record field in the UniFFI-generated record:
/// the declared name, snake_cased by the Rust backend, camelized back by
/// UniFFI — an identity for conventional camelCase field names.
fn ffi_field_label(name: &str) -> String {
    lower_camel(&snake_case(name))
}

/// True when a value of this type changes representation at the FFI
/// boundary (Bool/Float/String pass through untouched).
fn needs_conversion(ty: &ir::Type) -> bool {
    match ty {
        ir::Type::Int | ir::Type::Record(_) => true,
        ir::Type::List(inner) => needs_conversion(inner),
        _ => false,
    }
}

/// nui Swift value → FFI value: Int widens to Int64; records convert
/// field-wise into the component-prefixed UniFFI record; lists map their
/// elements.
fn to_ffi(component: &ir::Component, param: &ir::Param) -> String {
    convert_to_ffi(component, &param.ty, &param.name)
}

fn convert_to_ffi(component: &ir::Component, ty: &ir::Type, expr: &str) -> String {
    match ty {
        ir::Type::Int => format!("Int64({expr})"),
        ir::Type::Record(record_name) => {
            let record = record_decl(component, record_name);
            let fields: Vec<String> = record
                .fields
                .iter()
                .map(|field| {
                    format!(
                        "{}: {}",
                        ffi_field_label(&field.name),
                        convert_to_ffi(component, &field.ty, &format!("{expr}.{}", field.name))
                    )
                })
                .collect();
            format!(
                "{}({})",
                rust_record_name(&component.name, record_name),
                fields.join(", ")
            )
        }
        ir::Type::List(inner) if needs_conversion(inner) => {
            format!("{expr}.map {{ {} }}", convert_to_ffi(component, inner, "$0"))
        }
        _ => expr.to_string(),
    }
}

/// FFI result → nui Swift value: the mirror of [`convert_to_ffi`].
fn from_ffi(component: &ir::Component, ty: &ir::Type, expr: &str) -> String {
    match ty {
        ir::Type::Int => format!("Int({expr})"),
        ir::Type::Record(record_name) => {
            let record = record_decl(component, record_name);
            let fields: Vec<String> = record
                .fields
                .iter()
                .map(|field| {
                    format!(
                        "{}: {}",
                        field.name,
                        from_ffi(
                            component,
                            &field.ty,
                            &format!("{expr}.{}", ffi_field_label(&field.name))
                        )
                    )
                })
                .collect();
            format!("{record_name}({})", fields.join(", "))
        }
        ir::Type::List(inner) if needs_conversion(inner) => {
            format!("{expr}.map {{ {} }}", from_ffi(component, inner, "$0"))
        }
        _ => expr.to_string(),
    }
}
