//! UIKit backend (experimental): transpiles the IR into a single drop-in
//! UIKit file — real system controls, no SwiftUI anywhere.
//!
//! For a component named `Counter` the generated file contains:
//!
//! - `CounterState` / `CounterLogic` — identical to the SwiftUI backend's,
//!   so the generated Rust bridge and logic crate work with either UI.
//! - `CounterStore` — plain `@MainActor` class. Instead of `@Observable`
//!   it calls `onChange` after every logic-driven state change; text
//!   fields mutate their bound state through generated setters.
//! - `CounterViewController` — builds the view tree once out of
//!   `UIStackView`/`UILabel`/`UIButton`/…, then applies state changes
//!   directly in `applyState()`. There is no diffing engine: the compiler
//!   knows statically which views depend on which state, so it generates
//!   the exact imperative updates SwiftUI would compute at runtime.
//! - a DEBUG-only `#Preview` with a stub logic returning default values.
//!
//! v0 limitations, on purpose: `List` renders as a plain vertical stack
//! (`UITableView` mapping is TODO), and `font` on containers does not
//! cascade to children the way SwiftUI's environment does.

use crate::ir;
use crate::swift::{
    call_args, default_value, emit_logic, emit_state, emit_types, number, protocol_method,
    string_literal, swift_type, text_literal, upper_first, ActionMethods, Writer,
};

pub fn generate(doc: &ir::Document) -> String {
    let component = &doc.component;
    let actions = ActionMethods::collect(component);
    let mut w = Writer::default();

    w.line("// Generated by nui — do not edit.");
    w.line(format!(
        "// Component: {} (IR format v{}) — UIKit backend (experimental)",
        component.name, doc.format_version
    ));
    w.blank();
    w.line("import UIKit");
    w.blank();

    emit_types(&mut w, component);
    emit_state(&mut w, component);
    emit_logic(&mut w, component);
    emit_store(&mut w, component, &actions);
    emit_view_controller(&mut w, component, &actions);
    emit_pad_helper(&mut w);
    emit_preview(&mut w, component);

    w.out
}

fn emit_store(w: &mut Writer, component: &ir::Component, actions: &ActionMethods) {
    let name = &component.name;
    w.line("// MARK: - Store");
    w.blank();
    w.line("@MainActor");
    w.line(format!("public final class {name}Store {{"));
    w.indented(|w| {
        w.line(format!("public private(set) var state: {name}State"));
        w.line("/// Called on the main actor after every logic-driven state change.");
        w.line("public var onChange: (@MainActor () -> Void)?");
        w.line(format!("private let logic: any {name}Logic"));
        w.blank();
        w.line(format!(
            "public init(logic: any {name}Logic, state: {name}State = {name}State()) {{"
        ));
        w.indented(|w| {
            w.line("self.logic = logic");
            w.line("self.state = state");
        });
        w.line("}");
        for (action, method) in &actions.methods {
            w.blank();
            w.line(format!("public func {method}() {{"));
            w.indented(|w| {
                w.line("Task {");
                w.indented(|w| {
                    w.line(format!(
                        "state.{} = await logic.{}({})",
                        action.state,
                        action.function,
                        call_args(component, action)
                    ));
                    w.line("onChange?()");
                });
                w.line("}");
            });
            w.line("}");
        }
        let mut bindings = Vec::new();
        collect_bindings(&component.root, &mut bindings);
        for binding in &bindings {
            w.blank();
            w.line("/// Local, UI-owned mutation from the bound text field.");
            w.line(format!(
                "public func set{}(_ value: String) {{",
                upper_first(binding)
            ));
            w.indented(|w| w.line(format!("state.{binding} = value")));
            w.line("}");
        }
    });
    w.line("}");
    w.blank();
}

fn collect_bindings(node: &ir::Node, out: &mut Vec<String>) {
    match node {
        ir::Node::TextField { binding, .. } => {
            if !out.contains(binding) {
                out.push(binding.clone());
            }
        }
        ir::Node::VStack { children, .. }
        | ir::Node::HStack { children, .. }
        | ir::Node::List { children, .. } => {
            for child in children {
                collect_bindings(child, out);
            }
        }
        ir::Node::If {
            then_children,
            else_children,
            ..
        } => {
            for child in then_children.iter().chain(else_children) {
                collect_bindings(child, out);
            }
        }
        ir::Node::For { children, .. } => {
            for child in children {
                collect_bindings(child, out);
            }
        }
        _ => {}
    }
}

/// Layout context an `if` branch inherits from its enclosing stack, so
/// branch children are laid out exactly like their siblings.
struct StackCtx {
    axis: &'static str,
    alignment: &'static str,
    spacing: Option<f64>,
}

const ROOT_CTX: StackCtx = StackCtx {
    axis: "vertical",
    alignment: ".center",
    spacing: None,
};

fn emit_view_controller(w: &mut Writer, component: &ir::Component, actions: &ActionMethods) {
    let name = &component.name;
    let mut vc = Vc {
        component,
        actions,
        decls: Vec::new(),
        build: Writer {
            out: String::new(),
            indent: 2,
        },
        apply: Vec::new(),
        rows: Vec::new(),
        in_row: false,
        next_id: 0,
    };
    let mut root_names = vc.emit_node(&component.root, &ROOT_CTX);
    debug_assert_eq!(root_names.len(), 1, "the root is always a single view");
    let root = root_names.remove(0);

    w.line("// MARK: - View Controller");
    w.blank();
    w.line(format!(
        "public final class {name}ViewController: UIViewController {{"
    ));
    w.indented(|w| {
        w.line(format!("private let store: {name}Store"));
        if !vc.decls.is_empty() {
            w.blank();
            for decl in &vc.decls {
                w.line(decl);
            }
        }
        w.blank();
        w.line(format!("public init(store: {name}Store) {{"));
        w.indented(|w| {
            w.line("self.store = store");
            w.line("super.init(nibName: nil, bundle: nil)");
        });
        w.line("}");
        w.blank();
        w.line("@available(*, unavailable)");
        w.line("public required init?(coder: NSCoder) {");
        w.indented(|w| w.line("fatalError(\"init(coder:) is not supported\")"));
        w.line("}");
        w.blank();
        w.line("public override func viewDidLoad() {");
        w.indented(|w| {
            w.line("super.viewDidLoad()");
            w.line("view.backgroundColor = .systemBackground");
            w.blank();
            w.line("let root = buildViewTree()");
            w.line("root.translatesAutoresizingMaskIntoConstraints = false");
            w.line("view.addSubview(root)");
            w.line("NSLayoutConstraint.activate([");
            w.indented(|w| {
                w.line("root.centerXAnchor.constraint(equalTo: view.safeAreaLayoutGuide.centerXAnchor),");
                w.line("root.centerYAnchor.constraint(equalTo: view.safeAreaLayoutGuide.centerYAnchor),");
                w.line("root.leadingAnchor.constraint(greaterThanOrEqualTo: view.safeAreaLayoutGuide.leadingAnchor),");
                w.line("root.trailingAnchor.constraint(lessThanOrEqualTo: view.safeAreaLayoutGuide.trailingAnchor),");
            });
            w.line("])");
            w.blank();
            w.line("store.onChange = { [weak self] in self?.applyState() }");
            w.line("applyState()");
        });
        w.line("}");
        w.blank();
        w.line("private func buildViewTree() -> UIView {");
    });
    w.out.push_str(&vc.build.out);
    w.indented(|w| {
        w.indented(|w| w.line(format!("return {root}")));
        w.line("}");
        w.blank();
        w.line("/// Applies state to the bound views directly. No diffing: the");
        w.line("/// compiler knows exactly which views depend on which state.");
        w.line("private func applyState() {");
        w.indented(|w| {
            for line in &vc.apply {
                w.line(line);
            }
        });
        w.line("}");
    });
    for row in &vc.rows {
        w.blank();
        w.out.push_str(row);
    }
    w.line("}");
    w.blank();
}

/// Walks the IR tree emitting `buildViewTree()` code. State-bound views
/// become stored properties (declared in `decls`, updated in `apply`);
/// everything else is a local. Returns the variable naming each node's
/// final view (after padding wraps).
struct Vc<'a> {
    component: &'a ir::Component,
    actions: &'a ActionMethods,
    decls: Vec<String>,
    build: Writer,
    apply: Vec<String>,
    /// Fully formatted `makeRow` methods, one per `for` loop.
    rows: Vec<String>,
    /// Inside a row builder everything is emitted inline (rows are rebuilt
    /// wholesale on every state change), never as stored properties.
    in_row: bool,
    next_id: usize,
}

impl Vc<'_> {
    fn next(&mut self) -> usize {
        let id = self.next_id;
        self.next_id += 1;
        id
    }

    /// Blank line between view blocks for readability.
    fn begin_block(&mut self) {
        if !self.build.out.is_empty() {
            self.build.blank();
        }
    }

    /// Emits one IR node; returns the view name(s) the parent should add.
    /// Every node yields exactly one view except `if`, which yields a
    /// container per branch (at most one is visible at a time).
    fn emit_node(&mut self, node: &ir::Node, parent: &StackCtx) -> Vec<String> {
        match node {
            ir::Node::Text { content, modifiers } => {
                self.begin_block();
                let name = format!("label{}", self.next());
                if !self.in_row && is_dynamic(content) {
                    self.decls.push(format!("private let {name} = UILabel()"));
                    self.apply
                        .push(format!("{name}.text = {}", text_literal(content)));
                } else {
                    self.build.line(format!("let {name} = UILabel()"));
                    self.build
                        .line(format!("{name}.text = {}", text_literal(content)));
                }
                self.build.line(format!("{name}.numberOfLines = 0"));
                self.style_lines(&name, modifiers, "textColor", Some("font"));
                vec![self.wrap_padding(name, modifiers)]
            }
            ir::Node::Button {
                label,
                action,
                modifiers,
            } => {
                self.begin_block();
                let name = format!("button{}", self.next());
                let method = self.actions.name_for(action).to_string();
                if !self.in_row && is_dynamic(label) {
                    self.decls
                        .push(format!("private let {name} = UIButton(type: .system)"));
                    self.build.line(format!(
                        "{name}.addAction(UIAction {{ [weak self] _ in self?.store.{method}() }}, for: .touchUpInside)"
                    ));
                    self.apply.push(format!(
                        "{name}.setTitle({}, for: .normal)",
                        text_literal(label)
                    ));
                } else {
                    self.build.line(format!(
                        "let {name} = UIButton(type: .system, primaryAction: UIAction(title: {}) {{ [weak self] _ in",
                        text_literal(label)
                    ));
                    self.build
                        .indented(|w| w.line(format!("self?.store.{method}()")));
                    self.build.line("})");
                }
                self.style_lines(&name, modifiers, "tintColor", Some("titleLabel?.font"));
                vec![self.wrap_padding(name, modifiers)]
            }
            ir::Node::TextField {
                binding,
                placeholder,
                modifiers,
            } => {
                self.begin_block();
                let name = format!("textField{}", self.next());
                self.decls
                    .push(format!("private let {name} = UITextField()"));
                if let Some(placeholder) = placeholder {
                    self.build.line(format!(
                        "{name}.placeholder = {}",
                        string_literal(placeholder)
                    ));
                }
                self.build.line(format!("{name}.borderStyle = .roundedRect"));
                self.build
                    .line(format!("{name}.addAction(UIAction {{ [weak self] _ in"));
                self.build.indented(|w| {
                    w.line("guard let self else { return }");
                    w.line(format!(
                        "self.store.set{}(self.{name}.text ?? \"\")",
                        upper_first(binding)
                    ));
                });
                self.build.line("}, for: .editingChanged)");
                // Guarded so applying state never clobbers in-progress typing.
                self.apply.push(format!(
                    "if {name}.text != store.state.{binding} {{ {name}.text = store.state.{binding} }}"
                ));
                self.style_lines(&name, modifiers, "textColor", Some("font"));
                vec![self.wrap_padding(name, modifiers)]
            }
            ir::Node::Image { source, modifiers } => {
                self.begin_block();
                let name = format!("image{}", self.next());
                self.build.line(format!(
                    "let {name} = UIImageView(image: UIImage(named: {}))",
                    string_literal(source)
                ));
                self.build.line(format!("{name}.contentMode = .scaleAspectFit"));
                self.style_lines(&name, modifiers, "tintColor", None);
                vec![self.wrap_padding(name, modifiers)]
            }
            ir::Node::VStack {
                spacing,
                children,
                modifiers,
            } => vec![self.stack("vertical", ".center", *spacing, children, modifiers)],
            ir::Node::HStack {
                spacing,
                children,
                modifiers,
            } => vec![self.stack("horizontal", ".center", *spacing, children, modifiers)],
            ir::Node::List {
                children,
                modifiers,
            } => {
                let name = self.stack("vertical", ".fill", None, children, modifiers);
                self.build
                    .line("// nui: List renders as a plain stack for now (UITableView mapping is TODO).");
                vec![name]
            }
            ir::Node::Spacer => {
                self.begin_block();
                let name = format!("spacer{}", self.next());
                self.build.line(format!("let {name} = UIView()"));
                self.build.line(format!(
                    "{name}.setContentHuggingPriority(.defaultLow, for: .horizontal)"
                ));
                self.build.line(format!(
                    "{name}.setContentHuggingPriority(.defaultLow, for: .vertical)"
                ));
                vec![name]
            }
            ir::Node::If {
                condition,
                then_children,
                else_children,
            } => {
                let mut names = vec![self.branch(condition, false, then_children, parent)];
                if !else_children.is_empty() {
                    names.push(self.branch(condition, true, else_children, parent));
                }
                names
            }
            ir::Node::For {
                binding,
                source,
                children,
            } => {
                let id = self.next();
                let name = format!("forStack{id}");
                let row_fn = format!("makeRow{id}");
                self.decls
                    .push(format!("private let {name} = UIStackView()"));
                self.begin_block();
                self.build.line(format!("{name}.axis = .{}", parent.axis));
                self.build
                    .line(format!("{name}.alignment = {}", parent.alignment));
                if let Some(spacing) = parent.spacing {
                    self.build
                        .line(format!("{name}.spacing = {}", number(spacing)));
                }
                self.emit_row_builder(&row_fn, binding, source, children, parent);
                self.apply.push(format!(
                    "{name}.arrangedSubviews.forEach {{ $0.removeFromSuperview() }}"
                ));
                self.apply.push(format!(
                    "for {binding} in store.state.{source} {{ \
                     {name}.addArrangedSubview({row_fn}({binding})) }}"
                ));
                vec![name]
            }
        }
    }

    /// Emits the `makeRow` method for one `for` loop. Rows contain no
    /// stored properties or `applyState()` lines: every state change
    /// rebuilds all rows, so their content is always current.
    fn emit_row_builder(
        &mut self,
        row_fn: &str,
        binding: &str,
        source: &str,
        children: &[ir::Node],
        parent: &StackCtx,
    ) {
        let element = element_type(self.component, source);
        let saved_build = std::mem::replace(
            &mut self.build,
            Writer {
                out: String::new(),
                indent: 2,
            },
        );
        self.in_row = true;
        let mut names: Vec<String> = children
            .iter()
            .flat_map(|child| self.emit_node(child, parent))
            .collect();
        let root = if names.len() == 1 {
            names.remove(0)
        } else {
            // Multiple views per element: group them so each element still
            // contributes exactly one arranged subview.
            let wrap = format!("row{}", self.next());
            self.begin_block();
            self.build.line(format!(
                "let {wrap} = UIStackView(arrangedSubviews: [{}])",
                names.join(", ")
            ));
            self.build.line(format!("{wrap}.axis = .{}", parent.axis));
            self.build
                .line(format!("{wrap}.alignment = {}", parent.alignment));
            if let Some(spacing) = parent.spacing {
                self.build
                    .line(format!("{wrap}.spacing = {}", number(spacing)));
            }
            wrap
        };
        self.in_row = false;
        let body = std::mem::replace(&mut self.build, saved_build);

        let mut method = Writer {
            out: String::new(),
            indent: 1,
        };
        method.line(format!(
            "/// Builds one row of `for {binding} in {source}`. Rows are rebuilt"
        ));
        method.line("/// wholesale in `applyState()` — no diffing yet.");
        method.line(format!(
            "private func {row_fn}(_ {binding}: {}) -> UIView {{",
            swift_type(&element)
        ));
        method.out.push_str(&body.out);
        method.indented(|w| w.line(format!("return {root}")));
        method.line("}");
        self.rows.push(method.out);
    }

    /// One `if` branch becomes a stored container stack that inherits the
    /// parent's layout; `applyState()` toggles `isHidden`, and UIStackView
    /// removes hidden arranged subviews from layout — no diffing needed.
    fn branch(
        &mut self,
        condition: &str,
        negated: bool,
        children: &[ir::Node],
        parent: &StackCtx,
    ) -> String {
        let child_names: Vec<String> = children
            .iter()
            .flat_map(|child| self.emit_node(child, parent))
            .collect();
        self.begin_block();
        let name = format!("branch{}", self.next());
        self.decls
            .push(format!("private let {name} = UIStackView()"));
        for child in &child_names {
            self.build
                .line(format!("{name}.addArrangedSubview({child})"));
        }
        self.build.line(format!("{name}.axis = .{}", parent.axis));
        self.build
            .line(format!("{name}.alignment = {}", parent.alignment));
        if let Some(spacing) = parent.spacing {
            self.build
                .line(format!("{name}.spacing = {}", number(spacing)));
        }
        self.apply.push(if negated {
            format!("{name}.isHidden = store.state.{condition}")
        } else {
            format!("{name}.isHidden = !store.state.{condition}")
        });
        name
    }

    fn stack(
        &mut self,
        axis: &'static str,
        alignment: &'static str,
        spacing: Option<f64>,
        children: &[ir::Node],
        modifiers: &[ir::Modifier],
    ) -> String {
        let ctx = StackCtx {
            axis,
            alignment,
            spacing,
        };
        let child_names: Vec<String> = children
            .iter()
            .flat_map(|child| self.emit_node(child, &ctx))
            .collect();
        self.begin_block();
        let name = format!("stack{}", self.next());
        self.build.line(format!(
            "let {name} = UIStackView(arrangedSubviews: [{}])",
            child_names.join(", ")
        ));
        self.build.line(format!("{name}.axis = .{axis}"));
        self.build.line(format!("{name}.alignment = {alignment}"));
        if let Some(spacing) = spacing {
            self.build
                .line(format!("{name}.spacing = {}", number(spacing)));
        }
        self.style_lines(&name, modifiers, "tintColor", None);
        self.wrap_padding(name, modifiers)
    }

    /// Emits font/color configuration for a view. `font_property` is None
    /// for views with no meaningful font target (containers, images).
    fn style_lines(
        &mut self,
        name: &str,
        modifiers: &[ir::Modifier],
        color_property: &str,
        font_property: Option<&str>,
    ) {
        for modifier in modifiers {
            match modifier {
                ir::Modifier::Font { style } => match font_property {
                    Some(property) => {
                        self.build.line(format!(
                            "{name}.{property} = UIFont.preferredFont(forTextStyle: .{})",
                            uifont(*style)
                        ));
                    }
                    None => {
                        self.build.line(format!(
                            "// nui: `font` on `{name}` has no UIKit equivalent (no environment cascade)."
                        ));
                    }
                },
                ir::Modifier::ForegroundColor { color } => {
                    self.build.line(format!(
                        "{name}.{color_property} = .{}",
                        uicolor(*color)
                    ));
                }
                ir::Modifier::Padding { .. } => {} // handled by wrap_padding
            }
        }
    }

    /// Each `padding` wraps the view in an inset container (`nuiPad`).
    fn wrap_padding(&mut self, mut name: String, modifiers: &[ir::Modifier]) -> String {
        for modifier in modifiers {
            if let ir::Modifier::Padding { value } = modifier {
                let wrapped = format!("padded{}", self.next());
                self.build.line(format!(
                    "let {wrapped} = nuiPad({name}, {})",
                    number(*value)
                ));
                name = wrapped;
            }
        }
        name
    }
}

fn is_dynamic(content: &ir::TextContent) -> bool {
    content
        .0
        .iter()
        .any(|segment| matches!(segment, ir::TextSegment::State { .. }))
}

/// The element type of a `for` loop's source list. The source is always a
/// plain state name in v1 (record fields cannot hold lists yet).
fn element_type(component: &ir::Component, source: &str) -> ir::Type {
    let decl = component
        .state
        .iter()
        .find(|state| state.name == source)
        .expect("the `for` source was checked during lowering");
    let ir::Type::List(inner) = &decl.ty else {
        unreachable!("the `for` source is always a list");
    };
    (**inner).clone()
}

fn emit_pad_helper(w: &mut Writer) {
    w.line("/// Wraps a view in a container inset on all sides (the `padding` style).");
    w.line("@MainActor");
    w.line("private func nuiPad(_ view: UIView, _ inset: CGFloat) -> UIView {");
    w.indented(|w| {
        w.line("let container = UIView()");
        w.line("view.translatesAutoresizingMaskIntoConstraints = false");
        w.line("container.addSubview(view)");
        w.line("NSLayoutConstraint.activate([");
        w.indented(|w| {
            w.line("view.topAnchor.constraint(equalTo: container.topAnchor, constant: inset),");
            w.line("view.leadingAnchor.constraint(equalTo: container.leadingAnchor, constant: inset),");
            w.line("view.trailingAnchor.constraint(equalTo: container.trailingAnchor, constant: -inset),");
            w.line("view.bottomAnchor.constraint(equalTo: container.bottomAnchor, constant: -inset),");
        });
        w.line("])");
        w.line("return container");
    });
    w.line("}");
    w.blank();
}

fn emit_preview(w: &mut Writer, component: &ir::Component) {
    let name = &component.name;
    w.line("#if DEBUG");
    w.line("/// Preview stub returning default values. Real logic is injected");
    w.line("/// by the host app.");
    w.line(format!("private struct {name}PreviewLogic: {name}Logic {{"));
    w.indented(|w| {
        for function in &component.functions {
            w.line(format!(
                "{} {{ {} }}",
                protocol_method(function),
                default_value(component, &function.returns)
            ));
        }
    });
    w.line("}");
    w.blank();
    w.line("#Preview {");
    w.indented(|w| {
        w.line(format!(
            "{name}ViewController(store: {name}Store(logic: {name}PreviewLogic()))"
        ));
    });
    w.line("}");
    w.line("#endif");
}

fn uifont(style: ir::FontStyle) -> &'static str {
    match style {
        ir::FontStyle::LargeTitle => "largeTitle",
        ir::FontStyle::Title => "title1",
        ir::FontStyle::Headline => "headline",
        ir::FontStyle::Body => "body",
        ir::FontStyle::Caption => "caption1",
    }
}

fn uicolor(color: ir::Color) -> &'static str {
    match color {
        ir::Color::Primary => "label",
        ir::Color::Secondary => "secondaryLabel",
        ir::Color::Red => "systemRed",
        ir::Color::Green => "systemGreen",
        ir::Color::Blue => "systemBlue",
        ir::Color::Orange => "systemOrange",
        ir::Color::Yellow => "systemYellow",
        ir::Color::Purple => "systemPurple",
        ir::Color::Gray => "systemGray",
    }
}
