// Generated by nui — do not edit.
// Bridges the nui-generated `TodoList` UI to the Rust logic crate via UniFFI.

struct RustTodoListLogic: TodoListLogic {
    func add(todos: [Todo]) async -> [Todo] {
        let result = todoListAdd(todos: todos.map { TodoListTodo(title: $0.title) })
        return result.map { Todo(title: $0.title) }
    }
    func clear(todos: [Todo]) async -> [Todo] {
        let result = todoListClear(todos: todos.map { TodoListTodo(title: $0.title) })
        return result.map { Todo(title: $0.title) }
    }
}
