// Generated by nui — do not edit.
// Bridges the nui-generated `Profile` UI to the Rust logic crate via UniFFI.

struct RustProfileLogic: ProfileLogic {
    func next(current: Person) async -> Person {
        let result = profileNext(current: ProfilePerson(name: current.name, bio: current.bio))
        return Person(name: result.name, bio: result.bio)
    }
}
