// Generated by nui — do not edit.
// Bridges the nui-generated `Counter` UI to the Rust logic crate via UniFFI.

struct RustCounterLogic: CounterLogic {
    func increment(count: Int) async -> Int {
        Int(counterIncrement(count: Int64(count)))
    }
    func decrement(count: Int) async -> Int {
        Int(counterDecrement(count: Int64(count)))
    }
}
