// Generated by nui — do not edit.
// Bridges the nui-generated `Toggle` UI to the Rust logic crate via UniFFI.

struct RustToggleLogic: ToggleLogic {
    func toggle(value: Bool) async -> Bool {
        toggleToggle(value: value)
    }
}
